In [2]:
import pandas as pd
import numpy as np

In [3]:
df_student = pd.read_csv("student.csv")
df_student

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2023-12-17
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-12

In [5]:
df_student['ชื่อ'] = df_student['ชื่อ'].fillna('ไม่ระบุ')

## ใช้คำสั่ง fillnaเพื่อแก้ไขชื่อ ที่เป็นNaN เปลี่ยนเป็นคำว่าไม่ระบุแทน

In [6]:
df_student

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2023-12-17
2,64003,ไม่ระบุ,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-12

In [7]:
df_student['อายุ'] = df_student['อายุ'].fillna(df_student['อายุ'].median())
df_student

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2023-12-17
2,64003,ไม่ระบุ,21.0,Male,Science,3.67,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,21.0,NaN,NaN,3.78,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,21.0,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-12

## ใช้คำสั่งนี้เพื่อแทนค่าอายุจากค่า Nanเป็นค่ามัธยฐาน

In [12]:
df_student.loc[df_student['อายุ'] > 100, 'อายุ'] = df_student['อายุ'].median()
df_student

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2023-12-17
2,64003,ไม่ระบุ,21.0,ชาย,วิทยาศาสตร์,3.67,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,21.0,ชาย,วิศวกรรมศาสตร์,3.12,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,21.0,ไม่ระบุ,ไม่ระบุ,3.78,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,NaN,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,ไม่ระบุ,3.23,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,21.0,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.0,ไม่ระบุ,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-01-12

## ใช้คำสั่งนี้เพื่อแทนอายุที่มากกว่า 100 ปีด้วยค่ามัธยฐาน

In [10]:
df_student['เพศ'] = df_student['เพศ'].fillna('ไม่ระบุ')
df_student['เพศ'] = df_student['เพศ'].replace({
    'ช': 'ชาย', 'ญ': 'หญิง','F':'หญิง','M':'ชาย',
    'Male': 'ชาย', 'Female': 'หญิง'
})
df_student

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2023-12-17
2,64003,ไม่ระบุ,21.0,ชาย,Science,3.67,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ชาย,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.0,หญิง,วิศวะ,3.89,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.0,ชาย,Arts,3.34,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,21.0,ไม่ระบุ,NaN,3.78,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.0,หญิง,Sci,3.67,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,21.0,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.0,ไม่ระบุ,Science,3.45,168.0,64.0,23.0,2024-01-12

## คำสั่งแรกใช้เพื่อเปลี่ยนข้อมูลเพศที่เป็นค่าNaN เป็นคำว่า ไม่ระบุ และคำสั่งที่สองใช้เพื่อแก้ไขข้อมูลเพศให้เป็นมาตรฐานเดียวกัน

In [11]:
df_student['คณะ'] = df_student['คณะ'].fillna('ไม่ระบุ')
df_student['คณะ'] = df_student['คณะ'].replace({
    'Science': 'วิทยาศาสตร์',
    'วิทย์': 'วิทยาศาสตร์',
    'คณะวิทยาศาสตร์': 'วิทยาศาสตร์',
    'Sci':'วิทยาศาสตร์','Liberal Arts':'ศิลปศาสตร์','ศิลป์':'ศิลปศาสตร์',
    'Arts':'ศิลปศาสตร์','Engineering':'วิศวกรรมศาสตร์','วิศวะ':'วิศวกรรมศาสตร์','วิศวฯ':'วิศวกรรมศาสตร์'
})
df_student

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2023-12-17
2,64003,ไม่ระบุ,21.0,ชาย,วิทยาศาสตร์,3.67,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,150.0,ชาย,วิศวกรรมศาสตร์,3.12,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,21.0,ไม่ระบุ,ไม่ระบุ,3.78,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,NaN,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,ไม่ระบุ,3.23,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,21.0,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.0,ไม่ระบุ,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-01-12

## คำสั่งแรกใช้เพื่อเปลี่ยนข้อมูลคณะที่เป็นค่าNaN เป็นคำว่า ไม่ระบุ และคำสั่งที่สองใช้เพื่อแก้ไขข้อมูลคณะต่างๆให้เป็นมาตรฐานเดียวกัน

In [13]:
df_student['GPA'] = df_student['GPA'].fillna(df_student['GPA'].mean())
df_student['GPA'] = df_student['GPA'].clip(lower=0, upper=4)
df_student

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.210000,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.450000,165.0,58.0,20.0,2023-12-17
2,64003,ไม่ระบุ,21.0,ชาย,วิทยาศาสตร์,3.670000,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,0.000000,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.890000,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,21.0,ชาย,วิศวกรรมศาสตร์,3.120000,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.000000,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.980000,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.340000,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.560000,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,21.0,ไม่ระบุ,ไม่ระบุ,3.780000,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,3.246111,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.230000,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.450000,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.670000,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.890000,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.010000,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,ไม่ระบุ,3.230000,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,21.0,ชาย,ศิลปศาสตร์,3.246111,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.0,ไม่ระบุ,วิทยาศาสตร์,3.450000,168.0,64.0,23.0,2024-01-12

## คำสั่งแรก แทนค่าเกรดเฉลี่ยที่เป็น NaN ด้วยค่ามัธยฐาน คำสั่งที่สองเป็นการแก้ไขขอบเขตเกรดให้เริ่มที่ 0.00 และไม่เกิน 4.00

In [14]:
df_student['ส่วนสูง_cm'] = df_student['ส่วนสูง_cm'].fillna(df_student['ส่วนสูง_cm'].mean())
df_student

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.0,20.0,2023-12-17
2,64003,ไม่ระบุ,21.0,ชาย,วิทยาศาสตร์,3.670000,175.000000,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,0.000000,168.000000,70.0,10.0,2024-01-28
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.0,30.0,2024-01-14
5,64006,กานต์,21.0,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.0,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.000000,158.000000,48.0,35.0,2023-12-17
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.0,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.0,28.0,2024-01-17
10,64011,ธีระ,21.0,ไม่ระบุ,ไม่ระบุ,3.780000,167.684211,68.0,NaN,2023-12-27
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,3.246111,171.000000,NaN,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.0,14.0,2024-02-02
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.0,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,ไม่ระบุ,3.230000,161.000000,50.0,27.0,2024-02-12
18,64019,รัตนา,21.0,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.0,ไม่ระบุ,วิทยาศาสตร์,3.450000,168.000000,64.0,23.0,2024-01-12

## ใช้เพื่อแก้ไขข้อมูลส่วนสูงที่เป็น NaN แทนด้วยค่ามัธยฐาน

In [15]:
df_student['น้ำหนัก_kg'] = df_student['น้ำหนัก_kg'].fillna(df_student['น้ำหนัก_kg'].mean())
df_student

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.0,2023-12-17
2,64003,ไม่ระบุ,21.0,ชาย,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,0.000000,168.000000,70.000000,10.0,2024-01-28
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.0,2024-01-14
5,64006,กานต์,21.0,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.000000,158.000000,48.000000,35.0,2023-12-17
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.0,2024-02-13
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.0,2024-01-17
10,64011,ธีระ,21.0,ไม่ระบุ,ไม่ระบุ,3.780000,167.684211,68.000000,NaN,2023-12-27
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.0,2024-01-28
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.0,2024-01-09
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.0,2024-02-02
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,ไม่ระบุ,3.230000,161.000000,50.000000,27.0,2024-02-12
18,64019,รัตนา,21.0,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,NaN,2024-01-26
19,64020,ลัดดา,22.0,ไม่ระบุ,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.0,2024-01-12

## ใช้เพื่อแก้ไขข้อมูลน้ำหนักที่เป็น NaN แทนด้วยค่ามัธยฐาน

In [16]:
df_student['ชั่วโมงเรียน_ต่อสัปดาห์'] = df_student['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(df_student['ชั่วโมงเรียน_ต่อสัปดาห์'].median())
df_student

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.0,2023-12-17
2,64003,ไม่ระบุ,21.0,ชาย,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,0.000000,168.000000,70.000000,10.0,2024-01-28
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.0,2024-01-14
5,64006,กานต์,21.0,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.000000,158.000000,48.000000,35.0,2023-12-17
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.0,2024-02-13
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.0,2024-01-17
10,64011,ธีระ,21.0,ไม่ระบุ,ไม่ระบุ,3.780000,167.684211,68.000000,21.5,2023-12-27
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.0,2024-01-28
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.0,2024-01-09
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.0,2024-02-02
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,ไม่ระบุ,3.230000,161.000000,50.000000,27.0,2024-02-12
18,64019,รัตนา,21.0,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.5,2024-01-26
19,64020,ลัดดา,22.0,ไม่ระบุ,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.0,2024-01-12

## ใช้เพื่อแก้ไขข้อมูลชั่วโมงเรียนที่เป็น NaN แทนด้วยค่ามัธยฐาน

In [17]:
df = df_student.drop_duplicates()
df_student

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.0,2023-12-17
2,64003,ไม่ระบุ,21.0,ชาย,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,0.000000,168.000000,70.000000,10.0,2024-01-28
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.0,2024-01-14
5,64006,กานต์,21.0,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.000000,158.000000,48.000000,35.0,2023-12-17
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.0,2024-02-13
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.0,2024-01-17
10,64011,ธีระ,21.0,ไม่ระบุ,ไม่ระบุ,3.780000,167.684211,68.000000,21.5,2023-12-27
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.0,2024-01-28
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.0,2024-01-09
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.0,2024-02-02
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,ไม่ระบุ,3.230000,161.000000,50.000000,27.0,2024-02-12
18,64019,รัตนา,21.0,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.5,2024-01-26
19,64020,ลัดดา,22.0,ไม่ระบุ,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.0,2024-01-12

## ใช้เพื่อตรวจสอบหาค่าที่ซ่ำกันทุก column และลบทิ้งให้เหลือเพียงแถวเดียว

In [18]:
df['วันที่ลงทะเบียน'] = pd.to_datetime(df['วันที่ลงทะเบียน'], errors='coerce')
df_student

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.0,2023-12-17
2,64003,ไม่ระบุ,21.0,ชาย,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,0.000000,168.000000,70.000000,10.0,2024-01-28
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.0,2024-01-14
5,64006,กานต์,21.0,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.000000,158.000000,48.000000,35.0,2023-12-17
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.0,2024-02-13
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.0,2024-01-17
10,64011,ธีระ,21.0,ไม่ระบุ,ไม่ระบุ,3.780000,167.684211,68.000000,21.5,2023-12-27
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.0,2024-01-28
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.0,2024-01-09
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.0,2024-02-02
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,ไม่ระบุ,3.230000,161.000000,50.000000,27.0,2024-02-12
18,64019,รัตนา,21.0,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.5,2024-01-26
19,64020,ลัดดา,22.0,ไม่ระบุ,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.0,2024-01-12

## ใช้เพื่อเปลี่ยนชนิดข้อมูลจาก string เป็น datetime เพื่อให้ใช้งานง่ายขึ้น

In [19]:
print("Missing values หลังแก้ไข:")
print(df.isnull().sum())
print("\nข้อมูลหลังแก้ไข:")
print(df.head())

Missing values หลังแก้ไข:
รหัสนักศึกษา               0
ชื่อ                       0
อายุ                       0
เพศ                        0
คณะ                        0
GPA                        0
ส่วนสูง_cm                 0
น้ำหนัก_kg                 0
ชั่วโมงเรียน_ต่อสัปดาห์    0
วันที่ลงทะเบียน            0
dtype: int64

ข้อมูลหลังแก้ไข:
   รหัสนักศึกษา      ชื่อ  อายุ   เพศ             คณะ   GPA  ส่วนสูง_cm  \
0         64001     สมชาย  20.0   ชาย     วิทยาศาสตร์  3.21       170.0
1         64002    สมหญิง  21.0  หญิง     วิทยาศาสตร์  3.45       165.0
2         64003   ไม่ระบุ  21.0   ชาย     วิทยาศาสตร์  3.67       175.0
3         64004  สมศักดิ์  22.0   ชาย     วิทยาศาสตร์  0.00       168.0
4         64005      สมใจ  19.0  หญิง  วิศวกรรมศาสตร์  3.89       160.0

   น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0   65.000000                     15.0      2024-02-06
1   58.000000                     20.0      2023-12-17
2   63.611111                     25.0      2024-01-08
3   70.000000                     10.0      2024-01-28
4   52.000000                     30.0      2024-01-14

## ใช้เพื่อแสดงข้อมูลต่างๆหลังแก้ไข ว่าแก้ไขอย่างไรบ้าง